ema_decay: 0.995
ema_start: 0
finetune_batch_size: 512
finetune_dropout_rate: 0.5
finetune_epochs: 1000
finetune_learning_rate: 4.0e-05
finetune_optimizer_momentum: 0.9
finetune_optimizer_nesterov: true
mpl_augment_cutout_const: 4
mpl_augment_magnitude: 16
mpl_augment_ops: '[''AutoContrast'', ''Equalize'', ''Invert'', ''Rotate'', ''Posterize'',
  ''Solarize'', ''Color'', ''Contrast'', ''Brightness'', ''Sharpness'', ''ShearX'',
  ''ShearY'', ''TranslateX'', ''TranslateY'', ''Cutout'', ''SolarizeAdd'']'
mpl_augment_translate_const: 4
mpl_batch_size: 64
mpl_epochs: 10000
mpl_label_smoothing: 0.15
mpl_num_augments: 2
mpl_optimizer_grad_bound: 1000000000.0
mpl_optimizer_momentum: 0.9
mpl_optimizer_nesterov: true
mpl_unlabeled_batch_size_multiplier: 7
student_dropout_rate: 0.2
student_learning_rate: 0.05
student_learning_rate_numwait: 500
student_learning_rate_warmup: 5000
teacher_dropout_rate: 0.2
teacher_learning_rate: 0.05
teacher_learning_rate_numwait: 0
teacher_learning_rate_warmup: 5000
uda_label_temperature: 0.7
uda_steps: 5000
uda_threshold: 0.6
uda_weight: 8.0
